/*	
 *  Actividad 2 del curso Programación II
 *	
 *  Universidad Mariano Gálvez de Guatemala
 *	
 *  Autor:
 *  Francisco Antonio De León Natareno
*/

package vista;

import modelo.Cliente;
import modelo.Conexion;

public class frm_cliente extends javax.swing.JFrame {
  // Declaracion global de un objeto de tipo "Cliente"
  Cliente obj_cliente;

  /**
   * Creates new form frm_cliente
   */
  public frm_cliente() {
      initComponents();
      // Instanciar el objeto
      obj_cliente = new Cliente();
      tbl_cliente.setModel(obj_cliente.leer());
  }
  
  public void selec_datos() {
    int fila = tbl_cliente.getSelectedRow();
    
    lbl_id.setText(tbl_cliente.getValueAt(fila, 0).toString());
    txt_nit.setText(tbl_cliente.getValueAt(fila, 1).toString());
    txt_nombres.setText(tbl_cliente.getValueAt(fila, 2).toString());
    txt_apellidos.setText(tbl_cliente.getValueAt(fila, 3).toString());
    txt_direccion.setText(tbl_cliente.getValueAt(fila, 4).toString());
    txt_telefono.setText(tbl_cliente.getValueAt(fila, 5).toString());
    txt_fn.setText(tbl_cliente.getValueAt(fila, 6).toString());
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    lbl_nit = new javax.swing.JLabel();
    txt_nit = new javax.swing.JTextField();
    lbl_nombres = new javax.swing.JLabel();
    txt_nombres = new javax.swing.JTextField();
    lbl_apellidos = new javax.swing.JLabel();
    txt_apellidos = new javax.swing.JTextField();
    lbl_direccion = new javax.swing.JLabel();
    txt_direccion = new javax.swing.JTextField();
    lbl_telefono = new javax.swing.JLabel();
    txt_telefono = new javax.swing.JTextField();
    lbl_fn = new javax.swing.JLabel();
    txt_fn = new javax.swing.JTextField();
    btn_aceptar = new javax.swing.JButton();
    btn_actualizar = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    tbl_cliente = new javax.swing.JTable();
    lbl_ID = new javax.swing.JLabel();
    lbl_id = new javax.swing.JLabel();
    btn_eliminar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    lbl_nit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    lbl_nit.setText("Nit");

    txt_nit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

    lbl_nombres.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    lbl_nombres.setText("Nombres");

    txt_nombres.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

    lbl_apellidos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    lbl_apellidos.setText("Apellidos");

    txt_apellidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

    lbl_direccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    lbl_direccion.setText("Dirección");

    txt_direccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

    lbl_telefono.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    lbl_telefono.setText("Teléfono");

    txt_telefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

    lbl_fn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    lbl_fn.setText("Fecha Nacimiento");

    txt_fn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

    btn_aceptar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    btn_aceptar.setText("Agregar");
    btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_aceptarActionPerformed(evt);
      }
    });

    btn_actualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    btn_actualizar.setText("Actualizar");
    btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_actualizarActionPerformed(evt);
      }
    });

    tbl_cliente.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    tbl_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tbl_clienteMouseClicked(evt);
      }
    });
    tbl_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        tbl_clienteKeyReleased(evt);
      }
    });
    jScrollPane1.setViewportView(tbl_cliente);

    lbl_ID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    lbl_ID.setText("Id");

    lbl_id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

    btn_eliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    btn_eliminar.setText("Eliminar");
    btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_eliminarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1)
      .addGroup(layout.createSequentialGroup()
        .addGap(30, 30, 30)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lbl_nit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lbl_nombres)
          .addComponent(lbl_apellidos)
          .addComponent(lbl_direccion)
          .addComponent(lbl_telefono)
          .addComponent(lbl_fn)
          .addComponent(lbl_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(52, 52, 52)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(txt_nombres)
              .addComponent(txt_apellidos)
              .addComponent(txt_direccion)
              .addComponent(txt_telefono)
              .addComponent(txt_fn, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
            .addGap(35, 35, 35)
            .addComponent(btn_aceptar)
            .addGap(18, 18, 18)
            .addComponent(btn_actualizar)
            .addGap(18, 18, 18)
            .addComponent(btn_eliminar))
          .addComponent(txt_nit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(90, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(33, 33, 33)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lbl_ID)
          .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lbl_nit)
          .addComponent(txt_nit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lbl_nombres)
          .addComponent(txt_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lbl_apellidos)
          .addComponent(txt_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lbl_direccion)
          .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lbl_telefono)
          .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lbl_fn)
          .addComponent(txt_fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_aceptar)
          .addComponent(btn_actualizar)
          .addComponent(btn_eliminar))
        .addGap(18, 18, 18)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
      // Enviar parametros del Constructor (valores de los elementos en el formulario)
      obj_cliente = new Cliente(0,txt_nit.getText(),txt_nombres.getText(),txt_apellidos.getText(),txt_direccion.getText(),txt_telefono.getText(),txt_fn.getText());
        
      obj_cliente.agregar();
      tbl_cliente.setModel(obj_cliente.leer());
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
      // Modificar el objeto con el boton "Actualizar"
      obj_cliente = new Cliente(Integer.valueOf(lbl_id.getText()),txt_nit.getText(),txt_nombres.getText(),txt_apellidos.getText(),txt_direccion.getText(),txt_telefono.getText(),txt_fn.getText());
        
      obj_cliente.actualizar();
      tbl_cliente.setModel(obj_cliente.leer());
    }//GEN-LAST:event_btn_actualizarActionPerformed

  private void tbl_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_clienteMouseClicked
    selec_datos();
  }//GEN-LAST:event_tbl_clienteMouseClicked

  private void tbl_clienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_clienteKeyReleased
    selec_datos();
  }//GEN-LAST:event_tbl_clienteKeyReleased

  private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
    obj_cliente = new Cliente();
    
    obj_cliente.setId(Integer.valueOf(lbl_id.getText()));
    obj_cliente.eliminar();
    tbl_cliente.setModel(obj_cliente.leer());
    
    // Limpiar campos despues de eliminar
    lbl_id.setText(null);
    txt_nit.setText(null);
    txt_nombres.setText(null);
    txt_apellidos.setText(null);
    txt_direccion.setText(null);
    txt_telefono.setText(null);
    txt_fn.setText(null);
  }//GEN-LAST:event_btn_eliminarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
          for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
              if ("Nimbus".equals(info.getName())) {
                  javax.swing.UIManager.setLookAndFeel(info.getClassName());
                  break;
              }
          }
      } catch (ClassNotFoundException ex) {
          java.util.logging.Logger.getLogger(frm_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
          java.util.logging.Logger.getLogger(frm_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
          java.util.logging.Logger.getLogger(frm_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
          java.util.logging.Logger.getLogger(frm_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
          public void run() {
              new frm_cliente().setVisible(true);
          }
      });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_aceptar;
  private javax.swing.JButton btn_actualizar;
  private javax.swing.JButton btn_eliminar;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lbl_ID;
  private javax.swing.JLabel lbl_apellidos;
  private javax.swing.JLabel lbl_direccion;
  private javax.swing.JLabel lbl_fn;
  private javax.swing.JLabel lbl_id;
  private javax.swing.JLabel lbl_nit;
  private javax.swing.JLabel lbl_nombres;
  private javax.swing.JLabel lbl_telefono;
  private javax.swing.JTable tbl_cliente;
  private javax.swing.JTextField txt_apellidos;
  private javax.swing.JTextField txt_direccion;
  private javax.swing.JTextField txt_fn;
  private javax.swing.JTextField txt_nit;
  private javax.swing.JTextField txt_nombres;
  private javax.swing.JTextField txt_telefono;
  // End of variables declaration//GEN-END:variables
}
